// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkCmjQwy5VVJo7GkR4trtDcFE7jauFDII',
    appId: '1:591996051847:web:ae596fb1473606f3103322',
    messagingSenderId: '591996051847',
    projectId: 'gitr-mainproject',
    authDomain: 'gitr-mainproject.firebaseapp.com',
    storageBucket: 'gitr-mainproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBZsIfNaMl9qhMESlzCBxV1BJP76wgjlc',
    appId: '1:591996051847:android:1bbae5040d2e7559103322',
    messagingSenderId: '591996051847',
    projectId: 'gitr-mainproject',
    storageBucket: 'gitr-mainproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsmDIsYo9MVnC0FpSXiqCLSjxotOiD9lk',
    appId: '1:591996051847:ios:46ddc4c6ec3c0736103322',
    messagingSenderId: '591996051847',
    projectId: 'gitr-mainproject',
    storageBucket: 'gitr-mainproject.appspot.com',
    iosBundleId: 'com.example.gitr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsmDIsYo9MVnC0FpSXiqCLSjxotOiD9lk',
    appId: '1:591996051847:ios:46ddc4c6ec3c0736103322',
    messagingSenderId: '591996051847',
    projectId: 'gitr-mainproject',
    storageBucket: 'gitr-mainproject.appspot.com',
    iosBundleId: 'com.example.gitr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkCmjQwy5VVJo7GkR4trtDcFE7jauFDII',
    appId: '1:591996051847:web:b3be66091b3799b3103322',
    messagingSenderId: '591996051847',
    projectId: 'gitr-mainproject',
    authDomain: 'gitr-mainproject.firebaseapp.com',
    storageBucket: 'gitr-mainproject.appspot.com',
  );
}
